server:
  port: 8082

spring:
  application:
    name: camunda-standalone
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=camunda_standalone
    username: admin
    password: admin
  sql:
    init:
      mode: always
  jpa:
    database: postgresql
    open-in-view: false
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true

camunda.bpm:
  admin-user:
    id: a
    password: a
    firstName: Admin
  default-number-of-retries: 1
  job-executor-acquire-by-priority: true
  filter:
    create: All tasks
  database:
    table_prefix: camunda_standalone.
  eventing:
    task: true
  generic-properties:
    properties:
      loggingContextBusinessKey: "custom.businessKey"